---
ignore:
  - "subprojects/**"
  - "tests/**"
coverage:
  status:
    project:
      default:
        target: 90%
        threshold: 10%
        base: auto
        paths:
          - "nxx/nxx/"
    patch:
      default:
        target: 90%
        threshold: 10%
        base: auto
        paths:
          - "nxx/nxx/"