---
coverage:
 ignore:
    - "*.test.cpp"
  status:
    project:
      default:
        target: 90%
        threshold: 0%
        base: auto
        paths:
          - "nxx/nxx/"
    patch:
      default:
        target: 90%
        threshold: 0%
        base: auto
        paths:
          - "nxx/nxx/"