---
version: '3'

env:
  BUILD_TYPE: '{{.BUILD_TYPE | default "debug"}}'
  BUILD_DIR: 'build'

dotenv: [ '.env' ]

tasks:
  setup:gcc-13:
    cmds:
      - meson setup {{.BUILD_DIR}} --buildtype {{.BUILD_TYPE}} --native-file native_file/{{OS}}-gcc-13.native_file {{.CLI_ARGS}} 
  setup:gcc-14:
    cmds:
      - meson setup {{.BUILD_DIR}} --buildtype {{.BUILD_TYPE}} --native-file native_file/{{OS}}-gcc-14.native_file {{.CLI_ARGS}} 
  setup:llvm-18:
    cmds:
      - meson setup {{.BUILD_DIR}} --buildtype {{.BUILD_TYPE}} --native-file native_file/{{OS}}-llvm-18.native_file {{.CLI_ARGS}}

  compile:
    cmds:
      - meson compile -C {{.BUILD_DIR}}
  
  test:
    cmds:
      - meson test -v -C {{.BUILD_DIR}}

  coverage:
    cmds:
      - ninja -C {{.BUILD_DIR}} coverage

