---
version: '3'

env:
  BUILD_TYPE: '{{.BUILD_TYPE | default "debug"}}'
  BUILD_DIR: 'build'

dotenv: [ '.env' ]

tasks:
  setup:
    cmds:
      - meson setup $BUILD_DIR --buildtype $BUILD_TYPE --native-file native_file/{{OS}}.native_file {{.CLI_ARGS}}
  compile:
    cmds:
      - meson compile -C $BUILD_DIR nxx
  compile-test:
    cmds:
      - meson compile -C $BUILD_DIR nxx.test
  test:
    cmds:
      - meson test -C $BUILD_DIR nxx:nxx
  generate-coverage:
    cmds:
      - ninja -C $BUILD_DIR coverage-xml

