---
version: '3'

env:
  BUILD_TYPE: '{{.BUILD_TYPE | default "debug"}}'
  BUILD_DIR: 'build'

dotenv: [ '.env' ]

tasks:
  setup:internal:
    internal: true
    cmds:
      - meson setup {{.BUILD_DIR}} --buildtype {{.BUILD_TYPE}} --native-file native_file/{{OS}}-{{.COMPILER}}.native_file {{.CLI_ARGS}} 
  setup:gcc-13:
    cmds:
      - task: setup:internal
        vars:
          COMPILER: gcc-13
  setup:gcc-14:
    cmds:
      - task: setup:internal
        vars:
          COMPILER: gcc-13
  setup:clang-18:
    cmds:
      - task: setup:internal
        vars:
          COMPILER: clang-18
  setup:wipe:
    cmds:
      - rm -r {{.BUILD_DIR}}

  compile:
    cmds:
      - meson compile -C {{.BUILD_DIR}}
  
  test:
    cmds:
      - meson test -v -C {{.BUILD_DIR}}

  coverage:generate:
    cmds:
      - ninja -C {{.BUILD_DIR}} coverage

  coverage:enable:
    cmds:
      - meson configure {{.BUILD_DIR}} -Db_coverage=true

  coverage:disable:
    cmds:
      - meson configure {{.BUILD_DIR}} -Db_coverage=false

