---
version: '3'

env:
  BUILD_TYPE: '{{.BUILD_TYPE | default "debug"}}'
  BUILD_DIR: 'build'
  GCC_VERSION: '14'
  LLVM_VERSION: '18'

dotenv: [ '.env' ]

tasks:
  setup:gcc:
    cmds:
      - meson setup {{.BUILD_DIR}} --buildtype {{.BUILD_TYPE}} --native-file native_file/{{OS}}-gcc-{{.GCC_VERSION}}.native_file {{.CLI_ARGS}} 
  setup:llvm:
    cmds:
      - meson setup {{.BUILD_DIR}} --buildtype {{.BUILD_TYPE}} --native-file native_file/{{OS}}-llvm-{{.LLVM_VERSION}}.native_file {{.CLI_ARGS}}

  compile:
    cmds:
      - meson compile -C {{.BUILD_DIR}}
  
  test:
    cmds:
      - meson test -C {{.BUILD_DIR}}

  generate-coverage:
    cmds:
      - ninja -C {{.BUILD_DIR}} coverage

