---
name: CI

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  test-debug-coverage:
    name: Test Debug and Coverage
    runs-on: ubuntu-22.04
    container: 3uclid3/nos-buildenv:latest

    strategy:
      fail-fast: false
      matrix:
        compiler: [clang-18, gcc-13]
        
    steps:
      - name: Checkout
        uses: actions/checkout@v4
          
      - name: Setup
        run: |
            task setup:${{ matrix.compiler }} BUILD_TYPE=debug -- -Db_coverage=true

      - name: Compile
        run: |
          task compile

      - name: Test
        run: |
          task test
          
      - name: Coverage reports
        run: |
          task coverage
          
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
  
  test-release:
    name: Test Release
    runs-on: ubuntu-22.04
    container: 3uclid3/nos-buildenv:latest

    strategy:
      fail-fast: false
      matrix:
        compiler: [clang-18, gcc-13]
        
    steps:
      - name: Checkout
        uses: actions/checkout@v4
          
      - name: Setup
        run: |
            task setup:${{ matrix.compiler }} BUILD_TYPE=release

      - name: Compile
        run: |
          task compile

      - name: Test
        run: |
          task test
