---
name: CI

on:
  push:
  pull_request:
    branches:
      - main
jobs:
  test:
    name: test
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: false
      matrix:
        build-type: [debug, release]
        
    steps:
      - name: Install
        run: |
          sudo apt-get update
          sudo apt-get install -y wget gnupg lsb-release
          sudo apt-get install -y meson ninja-build
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 18
          sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-18 100
          sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-18 100
          sudo update-alternatives --install /usr/bin/ld.lld ld.lld /usr/bin/lld-18 100
          
      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x

      - name: Checkout
        uses: actions/checkout@v4
          
      - name: Setup build
        run: |
          task setup BUILD_TYPE=${{ matrix.build-type }}

      - name: Compile
        run: |
          task compile

      - name: Test
        run: |
          task test