---
name: CI

on:
  push:
  pull_request:
    branches:
      - main
jobs:
  test:
    name: test
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: false
      matrix:
        build-type: [debug, release]
        
    steps:
      - name: Install
        run: |
          sudo apt-get update
          sudo apt-get install -y wget gnupg lsb-release
          sudo apt-get install -y build-essential ccache python3 python3-pip
          sudo apt-get install -y meson ninja-build
          sudo pip3 install gcovr
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 18
          sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-18 100
          sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-18 100
          sudo update-alternatives --install /usr/bin/ld.lld ld.lld /usr/bin/lld-18 100
          
      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x

      - name: Checkout
        uses: actions/checkout@v4
          
      - name: Setup build
        run: |
          if [ "${{ matrix.build-type }}" == "debug" ]; then
            task setup BUILD_TYPE=${{ matrix.build-type }} -- -Db_coverage=true;
          else
            task setup BUILD_TYPE=${{ matrix.build-type }};
          fi

      - name: Compile
        run: |
          task compile

      - name: Test
        run: |
          task test
          
      - name: Coverage report
        if: matrix.build-type == 'debug'
        run: |
          task generate-coverage
          
      - name: Upload coverage reports to Codecov
        if: matrix.build-type == 'debug'
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}