---
name: CI

on:
  push:
  pull_request:
    branches:
      - main
jobs:
  test-and-code-coverage:
    name: Test and Code Coverage
    runs-on: ubuntu-22.04
    container: 3uclid3/nos-buildenv:latest

    strategy:
      fail-fast: false
      matrix:
        build-type: [debug, release]
        
    steps:
      - name: Checkout
        uses: actions/checkout@v4
          
      - name: Setup build
        run: |
          if [ "${{ matrix.build-type }}" = "debug" ]; then
            task setup BUILD_TYPE=${{ matrix.build-type }} -- -Db_coverage=true;
          else
            task setup BUILD_TYPE=${{ matrix.build-type }};
          fi

      - name: Compile
        run: |
          task compile

      - name: Test
        run: |
          task test
          
      - name: Coverage report
        if: matrix.build-type == 'debug'
        run: |
          task generate-coverage
          
      - name: Upload coverage reports to Codecov
        if: matrix.build-type == 'debug'
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}